version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
  redpanda:
    image: redpandadata/redpanda:v24.1.5
    command: redpanda start --overprovisioned --smp 1 --memory 1G --mode dev-container --set redpanda.enable_idempotence=true
    ports:
      - "9092:9092"
      - "9644:9644"
  airflow:
    image: apache/airflow:2.9.3
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
    command: bash -c "airflow db init && airflow users create --role Admin --username admin --password admin --firstname a --lastname a --email a@a.a && airflow webserver & airflow scheduler"
    ports:
      - "8080:8080"
